// Copyright Peter Gilbert, All Rights Reserved

#pragma once

#include "CoreMinimal.h"
#include "UObject/Object.h"
#include "ReberuSettings.generated.h"

/**
 * Settings for Reberu.
 */
UCLASS(config=Game, defaultconfig, meta = (DisplayName="Reberu Settings"), Blueprintable, BlueprintType)
class REBERU_API UReberuSettings : public UDeveloperSettings{
	GENERATED_BODY()

public:
	/** Path in the project where reberu assets will be stored. */
	UPROPERTY(EditAnywhere, config, Category="Reberu")
	FString ReberuPath = "/Game/Reberu";

	/** Default box extend for doors generated by Reberu. */
	UPROPERTY(EditAnywhere, config, Category="Reberu")
	FVector DefaultDoorExtent = FVector(3.f, 50.f, 100.f);
};
